version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    ports:
      - "8000:8000"
      - "5555:5555" # For Prisma Studio
    env_file:
      - ./packages/backend/.env
    depends_on:
      - db
    networks:
      - streamfi-net

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - streamfi-net

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: streamfi
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - streamfi-net

volumes:
  postgres_data:

networks:
  streamfi-net:
    driver: bridge
